export const INGREDIENTS_MAP = {
  bananas: { name: "bananas", iconUrl: "🍌" },
  grapes: { name: "grapes", iconUrl: "🍇" },
  blueberries: { name: "blueberries", iconUrl: "🫐" },
  raspberries: { name: "raspberries", iconUrl: "🫐" },
  strawberries: { name: "strawberries", iconUrl: "🍓" },
  pineapple: { name: "pineapple", iconUrl: "🍍" },
  pomegranate: { name: "pomegranate", iconUrl: "🍎" },
  apples: { name: "apples", iconUrl: "🍎" },
  oranges: { name: "oranges", iconUrl: "🍊" },
  lemons: { name: "lemons", iconUrl: "🍋" },
  limes: { name: "limes", iconUrl: "🍋" },
  peaches: { name: "peaches", iconUrl: "🍑" },
  pears: { name: "pears", iconUrl: "🍐" },
  plums: { name: "plums", iconUrl: "🟣" },
  apricots: { name: "apricots", iconUrl: "🧡" },
  kiwis: { name: "kiwis", iconUrl: "🥝" },
  avocados: { name: "avocados", iconUrl: "🥑" },
  tomatoes: { name: "tomatoes", iconUrl: "🍅" },
  peppers: { name: "peppers", iconUrl: "🌶️" },
  carrots: { name: "carrots", iconUrl: "🥕" },
  beetroots: { name: "beetroots", iconUrl: "🟣" },
  parsnips: { name: "parsnips", iconUrl: "🤍" },
  courgettes: { name: "courgettes", iconUrl: "🥒" },
  cucumbers: { name: "cucumbers", iconUrl: "🥒" },
  radishes: { name: "radishes", iconUrl: "❤️" },
  broccoli: { name: "broccoli", iconUrl: "🥦" },
  mushrooms: { name: "mushrooms", iconUrl: "🍄" },
  onions: { name: "onions", iconUrl: "🧅" },
  shallots: { name: "shallots", iconUrl: "🧅" },
  garlic: { name: "garlic", iconUrl: "🧄" },
  ginger: { name: "ginger", iconUrl: "🟠" },
  potatoes: { name: "potatoes", iconUrl: "🥔" },
  "sweet potatoes": { name: "sweet potatoes", iconUrl: "🍠" },
  peas: { name: "peas", iconUrl: "🟢" },
  "green beans": { name: "green beans", iconUrl: "🫘" },
  basil: { name: "basil", iconUrl: "🌿" },
  parsley: { name: "parsley", iconUrl: "🌿" },
  coriander: { name: "coriander", iconUrl: "🌿" },
  mint: { name: "mint", iconUrl: "🌿" },
  thyme: { name: "thyme", iconUrl: "🌿" },
  rosemary: { name: "rosemary", iconUrl: "🌿" },
  sage: { name: "sage", iconUrl: "🌿" },
  eggs: { name: "eggs", iconUrl: "🥚" },
  cheese: { name: "cheese", iconUrl: "🧀" },
  butter: { name: "butter", iconUrl: "🧈" },
  milk: { name: "milk", iconUrl: "🥛" },
  yogurt: { name: "yogurt", iconUrl: "🥣" },
  bread: { name: "bread", iconUrl: "🍞" },
  flour: { name: "flour", iconUrl: "🌾" },
  rice: { name: "rice", iconUrl: "🍚" },
  pasta: { name: "pasta", iconUrl: "🍝" },
  noodles: { name: "noodles", iconUrl: "🍜" },
  salt: { name: "salt", iconUrl: "🧂" },
  sugar: { name: "sugar", iconUrl: "🍬" },
  oil: { name: "oil", iconUrl: "🫒" },
};