export const recipes = [
  {
    name: "Spaghetti Bolognese",
    slug: "spaghetti-bolognese",
    categories: ["Main Course", "Chicken"],
    images: ["/images/recipe.jpg"],
    servings: 2,
    handsOnTime: 15,
    handsOffTime: 30,
    instructions: [
      "Boil spaghetti according to package instructions.",
      "Cook beef and onion until browned.",
      "Add tomato sauce and simmer for 20 minutes.",
      "Serve sauce over spaghetti.",
    ],
    notes: "Can be frozen for up to 2 months.",
    ingredients: [
      { name: "Spaghetti", amount: "200g" },
      { name: "Ground beef", amount: "300g" },
      { name: "Tomato sauce", amount: "1 cup" },
      { name: "Onion", amount: "1, diced" },
    ],
    nutritionalValue: {
      kcal: 550,
      carbs: 60,
      fat: 25,
      protein: 30,
    },
    source: {
      name: "My Italian Kitchen",
      url: "https://example.com/spaghetti-bolognese",
    },
  },
  {
    name: "Chicken Curry",
    slug: "chicken-curry",
    categories: ["Main Course", "Chicken"],
    images: ["/images/recipe.jpg"],
    servings: 4,
    handsOnTime: 20,
    handsOffTime: 40,
    instructions: [
      "Cook onions until soft.",
      "Add chicken and brown.",
      "Add coconut milk and curry powder, simmer for 30 minutes.",
      "Serve with rice.",
    ],
    notes: "Can be served with naan bread.",
    ingredients: [
      { name: "Chicken breast", amount: "400g" },
      { name: "Coconut milk", amount: "1 can" },
      { name: "Curry powder", amount: "2 tbsp" },
      { name: "Onion", amount: "1, diced" },
    ],
    nutritionalValue: {
      kcal: 700,
      carbs: 50,
      fat: 40,
      protein: 60,
    },
    source: {
      name: "Asian Delights",
      url: "https://example.com/chicken-curry",
    },
  },
  {
    name: "Caesar Salad",
    slug: "caesar-salad",
    categories: ["Main Course", "Chicken", "Salad"],
    images: ["/images/recipe.jpg"],
    servings: 2,
    handsOnTime: 10,
    handsOffTime: 0,
    instructions: [
      "Chop lettuce and place in a bowl.",
      "Add parmesan, croutons, and dressing.",
      "Toss and serve.",
    ],
    notes: "Add grilled chicken for extra protein.",
    ingredients: [
      { name: "Romaine lettuce", amount: "1 head" },
      { name: "Parmesan cheese", amount: "50g" },
      { name: "Croutons", amount: "1 cup" },
      { name: "Caesar dressing", amount: "1/2 cup" },
    ],
    nutritionalValue: {
      kcal: 300,
      carbs: 20,
      fat: 18,
      protein: 12,
    },
    source: {
      name: "Healthy Kitchen",
      url: "https://example.com/caesar-salad",
    },
  },
  {
    name: "Beef Tacos Tacoticco",
    slug: "beef-tacos",
    categories: ["Main Course"],
    images: ["/images/recipe.jpg"],
    servings: 4,
    handsOnTime: 15,
    handsOffTime: 10,
    instructions: [
      "Brown ground beef in a pan.",
      "Fill taco shells with beef, cheese, lettuce, and sour cream.",
      "Serve immediately.",
    ],
    notes: "Top with salsa for extra flavor.",
    ingredients: [
      { name: "Ground beef", amount: "500g" },
      { name: "Taco shells", amount: "8" },
      { name: "Cheese", amount: "100g" },
      { name: "Lettuce", amount: "1/2 head, shredded" },
      { name: "Sour cream", amount: "1/2 cup" },
    ],
    nutritionalValue: {
      kcal: 850,
      carbs: 60,
      fat: 45,
      protein: 40,
    },
    source: {
      name: "Mexican Fiesta",
      url: "https://example.com/beef-tacos",
    },
  },
  {
    name: "Pancakes",
    slug: "pancakes",
    categories: ["Main Course", "Chicken", "Salad", "Breakfast"],
    images: ["/images/recipe.jpg"],
    servings: 4,
    handsOnTime: 10,
    handsOffTime: 5,
    instructions: [
      "Mix all ingredients until smooth.",
      "Heat a pan and pour batter to form pancakes.",
      "Cook until golden on both sides.",
      "Serve with syrup or fruit.",
    ],
    notes: "Perfect for a weekend brunch.",
    ingredients: [
      { name: "Flour", amount: "1 cup" },
      { name: "Milk", amount: "1 cup" },
      { name: "Egg", amount: "1" },
      { name: "Butter", amount: "2 tbsp, melted" },
      { name: "Sugar", amount: "1 tbsp" },
    ],
    nutritionalValue: {
      kcal: 350,
      carbs: 55,
      fat: 12,
      protein: 8,
    },
    source: {
      name: "Breakfast Basics",
      url: "https://example.com/pancakes",
    },
  },
];